version: '3.7'
services:
  web:
    build: ./web
    ports:
      - "5005:5000"
    environment:
      - INDEX_NAME=wikiqa
    depends_on:
      - elasticsearch
      - bertserving

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - "5601:5601"

  bertserving:
    build: ./bertserving
    ports:
      - "5555:5555"
      - "5556:5556"
    volumes:
      - ./bertserving/bert-jp:/model

volumes:
  es-data:
    driver: local
